# Generated by Django 6.0.3 on 2026-04-25 07:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_author_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to=blog.models.upload_filepath),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, upload_to=blog.models.upload_filepath),
        ),
    ]
